stages:
  - build

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
buildkitd:
  stage: build
  tags:
  - docker
  script:
  - mkdir -p ~/.docker
  - echo "{\"auths\":{\"https://${TENCENTREGISTRY}\":{\"username\":\"${TENCENT_REGISTRY_USER}\",\"password\":\"${TENCENT_REGISTRY_PASSWORD}\"}}}" > ~/.docker/config.json
  - docker build ./ -t ${TENCENTREGISTRY}/${CI_PROJECT_NAME}/${CI_COMMIT_REF_SLUG}:${CI_COMMIT_SHORT_SHA}
  - docker push ${TENCENTREGISTRY}/${CI_PROJECT_NAME}/${CI_COMMIT_REF_SLUG}:${CI_COMMIT_SHORT_SHA}
  - docker rmi ${TENCENTREGISTRY}/${CI_PROJECT_NAME}/${CI_COMMIT_REF_SLUG}:${CI_COMMIT_SHORT_SHA}
